<a href="https://colab.research.google.com/github/fatisepah/samples/blob/main/explanation_conv2d_and_randn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Load in relevant libraries, and alias where appropriate
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import numpy as np


In [49]:
# non-square kernels and unequal stride and with padding and dilation
#conv2d(tedade kanal vorodi,tedade filter,size filter)
m = nn.Conv2d(1, 3, 3, stride=1, padding=0)
#rand(4),ye doneh 1*4
#rand(4,2),ye doneh 4*2
#rand(tedade abaad,satr,soton),(2,3,2)--> 4 ta 3*2 
input = torch.randn(1,10, 10)
output = m(input)

print("input=",input)


print("---------------------------------------")


print("output=",output)
print("leninput=",np.shape(input))
print("lenoutput=",np.shape(output))

input= tensor([[[ 1.3723, -1.7213,  2.5574,  0.0489,  0.4264,  1.1048,  1.7135,
           0.5437,  0.4625,  0.8737],
         [ 0.4299, -0.1972, -1.0123,  1.7128, -1.1849, -0.7081, -1.4394,
          -1.0490, -0.2851, -0.0755],
         [-0.8991, -0.0610, -0.0281, -0.4268,  0.5733,  1.2298,  1.2039,
           1.1483, -0.1105, -0.0832],
         [ 0.5769,  1.6396, -0.3478,  0.3541, -2.7399,  1.0298,  0.2738,
          -0.8475, -0.8368, -1.2719],
         [ 1.0168,  0.6288, -1.8615,  0.8575, -0.0499, -1.6342,  0.8640,
           3.0899, -1.9714, -0.2667],
         [-0.1939, -1.2860,  0.1180, -0.2797, -0.2854,  1.0413,  0.3145,
           2.3540, -2.1819,  0.1648],
         [ 0.6698, -0.8472,  0.1968, -0.4137, -1.0233,  0.2050,  0.2559,
          -0.0377,  0.7358, -0.2478],
         [ 1.2882,  0.2209,  1.3946,  0.2096,  0.6108,  0.9395, -0.2148,
           0.3383, -0.8491,  0.7145],
         [ 1.1103, -0.1547,  0.6252, -0.4972,  0.1427, -0.7123,  0.1941,
          -0.1974, -0.4031,  1.9

In [21]:
torch.randn(4)

tensor([ 0.2718,  1.4277, -1.3344, -0.0594])

In [24]:
torch.randn(4,1)

tensor([[0.0898],
        [0.2280],
        [1.6680],
        [0.4257]])

In [25]:
torch.randn(4,1,1)

tensor([[[-0.3387]],

        [[ 0.3736]],

        [[-1.2016]],

        [[-1.5923]]])

In [18]:
torch.randn(4,2)


tensor([[-0.0579, -0.9774],
        [-0.8483,  2.6378],
        [-1.5463, -1.1576],
        [ 0.6752,  1.6292]])

In [27]:
torch.randn(2,4)

tensor([[ 0.5630,  2.9719,  0.4371, -0.8323],
        [ 1.6157, -0.6683, -1.0931,  0.7690]])

In [32]:
torch.randn(10,2)

tensor([[ 0.8181,  0.9488],
        [ 0.7436, -1.6711],
        [ 0.3181,  0.9728],
        [-0.2008,  1.8552],
        [ 0.6911, -0.4341],
        [ 1.7153,  0.2899],
        [-0.3273,  0.1930],
        [ 1.8455,  0.2847],
        [ 0.4407,  0.4133],
        [ 0.6805, -1.8420]])

In [26]:
torch.randn(4,2,1)


tensor([[[-0.9866],
         [ 1.1469]],

        [[ 0.0215],
         [-0.1033]],

        [[ 2.1239],
         [-1.2566]],

        [[-1.1504],
         [ 1.0733]]])

In [19]:
torch.randn(4,2,3)

tensor([[[-0.1419, -0.7446, -1.9468],
         [ 1.9038, -0.2272, -0.8766]],

        [[-0.6134, -2.0576, -1.0403],
         [-0.6149, -0.2239, -1.5353]],

        [[-0.1940, -1.9305, -1.6862],
         [-0.6654,  0.1102, -0.8854]],

        [[-1.5606, -0.3823,  1.4654],
         [-0.8736,  1.0130, -0.3677]]])

In [36]:
# With square kernels and equal stride
m = nn.Conv2d(1,5,3, stride=2)
input = torch.randn(1, 3, 5)
output = m(input)
print("input=",input)
print("---------------------------------------")
print("output=",output)

input= tensor([[[-1.2539,  0.0588,  0.2672, -1.0966, -0.0973],
         [-1.5800,  0.7166,  0.8888,  1.5826,  0.1351],
         [-1.2673, -1.3006,  1.3761, -0.1236, -1.2199]]])
---------------------------------------
output= tensor([[[-0.0722,  0.0089]],

        [[-0.0410,  0.3096]],

        [[-0.4875,  0.1599]],

        [[-0.2782,  0.8077]],

        [[-0.6167, -0.0760]]], grad_fn=<SqueezeBackward1>)


In [40]:
# With square kernels and equal stride
m = nn.Conv2d(1,2,3, stride=2)
input = torch.randn(1, 3, 5)
output = m(input)
print("input=",input)
print("---------------------------------------")
print("output=",output)

input= tensor([[[-1.3410,  0.9399,  0.1234, -0.1633, -0.9263],
         [ 1.5894, -0.0213, -1.4686,  0.9859,  1.5907],
         [ 1.6605, -2.2898,  0.6037,  0.3592, -1.5632]]])
---------------------------------------
output= tensor([[[-1.5296, -0.0662]],

        [[ 0.1646,  0.7222]]], grad_fn=<SqueezeBackward1>)


In [48]:
# With square kernels and equal stride
m = nn.Conv2d(1,5,(3,2), stride=1)
input = torch.randn(1, 5, 5)
output = m(input)
print("input=",input)
print("---------------------------------------")
print("output=",output)


input= tensor([[[ 6.1343e-04, -1.6910e+00, -7.4498e-01, -1.1026e+00,  5.4176e-01],
         [ 7.6395e-01,  1.6657e+00, -8.4342e-01,  2.7105e-01,  1.0905e+00],
         [ 4.6597e-01,  1.5214e+00,  2.0103e-01, -8.2304e-01, -1.3440e+00],
         [-8.2773e-01,  5.6822e-01, -1.6518e+00,  5.0152e-01, -2.9934e-01],
         [ 1.7612e+00, -1.0298e-01,  3.6415e-01,  1.2516e-02,  9.4491e-01]]])
---------------------------------------
output= tensor([[[-6.2807e-01, -1.2472e+00, -3.2869e-01, -9.1547e-01],
         [-3.7834e-01,  8.4898e-02, -1.3299e+00,  7.3970e-02],
         [ 6.0202e-01, -1.4220e-01,  2.6395e-01, -1.0362e+00]],

        [[-9.4400e-01, -9.5886e-01, -1.0589e+00, -3.4663e-04],
         [ 6.6140e-01, -8.1086e-01,  3.1066e-01, -2.4904e-01],
         [-4.5930e-01, -1.4497e-01, -1.0154e+00, -7.7006e-01]],

        [[ 1.6330e+00, -2.0761e-01, -9.0791e-02,  8.6821e-02],
         [ 1.0476e+00,  9.7702e-01, -6.1759e-02, -7.4782e-01],
         [-1.5295e-01,  2.5810e-01,  1.8271e-01,  4.271

In [37]:
# With square kernels and equal stride
m = nn.Conv2d(2,5,3, stride=2)
input = torch.randn(2, 3, 5)
output = m(input)
print("input=",input)
print("---------------------------------------")
print("output=",output)

input= tensor([[[ 0.4042, -1.9177,  1.5333, -0.0553,  1.2454],
         [-0.0293,  1.1067,  0.0930, -0.2053,  2.1103],
         [ 1.3539,  0.8512,  0.5079,  0.1876, -1.0166]],

        [[-1.0950,  2.0132,  0.3157, -0.3039, -1.3475],
         [ 0.0051, -0.5015, -0.9030, -0.4360, -1.5585],
         [ 1.7148, -0.2140, -0.1376,  1.1089,  0.3461]]])
---------------------------------------
output= tensor([[[ 0.1002, -0.6458]],

        [[-0.6913, -0.3933]],

        [[-0.0186, -0.1507]],

        [[ 0.1457,  0.1990]],

        [[-0.4219,  0.0109]]], grad_fn=<SqueezeBackward1>)


In [50]:

# non-square kernels and unequal stride and with padding
m = nn.Conv2d(2, 3, (3, 5), stride=(2, 1), padding=(4, 2))
# non-square kernels and unequal stride and with padding and dilation
m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2), dilation=(3, 1))
input = torch.randn(20, 16, 50, 100)
output = m(input)

https://keras.io/api/layers/convolution_layers/convolution2d/

In [53]:
from keras import activations
from keras import constraints
from keras import initializers
from keras import regularizers
from keras.dtensor import utils
from keras.layers.convolutional.base_conv import Conv
import tensorflow as tf
# isort: off
from tensorflow.python.util.tf_export import keras_export

# The inputs are 28x28 RGB images with `channels_last` and the batch
# size is 4.
input_shape = (4, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(2, 3, activation='relu', input_shape=input_shape[1:])(x)
print(y.shape)
print("input=",x)
print("---------------------------------------")
print("output=",y)

(4, 26, 26, 2)
input= tf.Tensor(
[[[[-1.5663702  -1.0364852   1.4140319 ]
   [ 0.80493855 -0.36754525 -0.7757288 ]
   [ 1.2731154   0.8112102  -0.10849063]
   ...
   [ 0.15332824 -0.54628855  0.601608  ]
   [ 1.2640084  -0.39056334  1.0794038 ]
   [ 0.9890917  -1.2546134   0.9209927 ]]

  [[-1.0140047  -0.3377701   0.661531  ]
   [-1.2552404   1.0997491   0.72710913]
   [-1.4482085   0.32883736  0.72449565]
   ...
   [ 0.48073256 -0.9431158  -0.06119485]
   [ 1.1175536  -0.20278752  0.2541447 ]
   [ 0.5440266  -0.28891906 -0.86399215]]

  [[ 0.8738568   0.12297042 -0.86933255]
   [-1.3327981   0.49483517  1.1274633 ]
   [-0.2896217  -1.9727652  -0.6069626 ]
   ...
   [-0.4128952   0.16701607  0.61480445]
   [-0.29150137  0.8747087  -0.07614355]
   [-1.2729911  -0.2468683   0.66025776]]

  ...

  [[-0.1710801   0.01759358 -0.10669235]
   [-0.38627827 -0.8901789  -1.7573017 ]
   [-0.64600223 -0.63846624  0.62523043]
   ...
   [-0.6418612  -0.7643832   0.01975665]
   [ 0.01174333 -0.66621

In [56]:
import tensorflow as tf
# isort: off
from tensorflow.python.util.tf_export import keras_export

# The inputs are 28x28 RGB images with `channels_last` and the batch
# size is 4.
input_shape = (1, 5, 5, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(2, 3, activation='relu', input_shape=input_shape[1:])(x)
print(y.shape)
print("input=",x)
print("---------------------------------------")
print("output=",y)

(1, 3, 3, 2)
input= tf.Tensor(
[[[[-0.8554609   0.31468785 -1.3766699 ]
   [ 0.7162438  -0.5636062  -0.24266587]
   [ 1.0898988  -0.22609733 -0.83834094]
   [ 1.2496996  -1.3307519  -0.991748  ]
   [-0.70879114 -0.14872648  1.2929945 ]]

  [[ 0.7051905  -0.5279035  -0.58488417]
   [-1.1669434   0.38574857 -0.6191213 ]
   [-0.04263498 -0.32746175  0.78787076]
   [-0.21342634 -0.09987131  1.7185451 ]
   [-1.4934739   0.18040141 -1.2179453 ]]

  [[-0.921405   -0.2749614   1.7975359 ]
   [-1.2633893  -0.9337027  -0.24559179]
   [-0.02269007  1.3875189  -0.24132244]
   [-1.1740223   1.0272591  -0.6428146 ]
   [ 1.8938755  -0.35635892 -1.0800856 ]]

  [[-0.16317745 -1.3496349   0.38896614]
   [-0.92556226  1.4426775  -0.50323695]
   [ 0.50191104  1.162102   -0.97897834]
   [ 0.5881627   0.49307343  0.22019301]
   [-2.5857377   2.3312771  -1.2370379 ]]

  [[ 0.8786402  -0.11288868 -0.9814523 ]
   [-0.014741   -0.63299125  1.6043385 ]
   [-0.83351785  0.46578658 -0.23150463]
   [ 0.11459862 -1

In [57]:
import tensorflow as tf
# isort: off
from tensorflow.python.util.tf_export import keras_export

# The inputs are 28x28 RGB images with `channels_last` and the batch
# size is 4.
input_shape = (1, 5, 5, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(2, 3, activation='relu',dilation_rate=2, input_shape=input_shape[1:])(x)
print(y.shape)
print("input=",x)
print("---------------------------------------")
print("output=",y)


(1, 1, 1, 2)
input= tf.Tensor(
[[[[-5.15664704e-02  1.76202416e+00 -5.74627221e-01]
   [ 1.93063855e+00 -1.83109546e+00 -3.37386817e-01]
   [ 1.37993252e+00 -1.34020185e+00 -1.73367485e-01]
   [-1.39272726e+00  1.89278376e+00  1.38892531e+00]
   [ 1.05188060e+00  1.00579786e+00  2.79699177e-01]]

  [[-1.15298533e+00 -9.96296883e-01 -4.86515015e-01]
   [ 1.33213234e+00 -6.69171512e-01 -4.90046561e-01]
   [-9.88977253e-02  8.06041896e-01  9.63863254e-01]
   [-1.07553184e-01 -5.55065274e-01 -1.24125719e+00]
   [-2.57205188e-01 -1.02040684e+00 -1.29613745e+00]]

  [[ 4.15840983e-01 -2.51172751e-01  2.73754984e-01]
   [-7.89349258e-01 -1.75784397e+00 -2.55684686e+00]
   [-1.99645245e+00 -5.33894897e-01  1.11988342e+00]
   [-1.90487158e+00 -4.87050302e-02 -3.96510839e-01]
   [ 8.02541494e-01  3.08020294e-01  8.29289556e-01]]

  [[-5.00046253e-01  8.88323367e-01  2.67761171e-01]
   [ 3.99879128e-01  5.96323133e-01  3.43018651e-01]
   [-4.07859504e-01 -1.30311394e+00  1.16838598e+00]
   [-6.58

In [58]:

import tensorflow as tf
# isort: off
from tensorflow.python.util.tf_export import keras_export

# The inputs are 28x28 RGB images with `channels_last` and the batch
# size is 4.
input_shape = (1, 5, 5, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(2, 3, activation='relu', padding="same", input_shape=input_shape[1:])(x)
print(y.shape)
print("input=",x)
print("---------------------------------------")
print("output=",y)

(1, 5, 5, 2)
input= tf.Tensor(
[[[[-1.7036337  -0.14072715  0.54748946]
   [-0.00915421  0.59886104 -0.7533636 ]
   [ 1.1956558   0.27903458 -0.8297382 ]
   [-0.9911834   1.3052263   0.6351209 ]
   [-0.19836755 -0.05502276 -0.35473454]]

  [[-0.12878743 -0.4603767   1.8757346 ]
   [ 0.43481043 -0.60962015 -1.0700675 ]
   [ 0.83416724 -2.5260496  -1.0657302 ]
   [ 1.0995541  -1.1995031  -0.4070651 ]
   [-0.9310222   0.8903939  -0.9380874 ]]

  [[-0.02583536 -1.1034502  -0.33942217]
   [-1.4771932   0.8014677   0.48389596]
   [ 2.2892847   1.012342   -0.9585913 ]
   [ 0.18317337 -0.5220102   1.4146488 ]
   [-0.7464921  -0.40225112  0.7661097 ]]

  [[ 1.1225202  -0.88978225 -0.87786597]
   [ 0.22837844 -1.1316515   0.05579556]
   [ 0.22665258 -0.7404162  -0.92434293]
   [-1.4379416   0.45645675  1.825174  ]
   [ 0.34022102  0.04285561  0.58213234]]

  [[-0.38645568  0.40002182  0.07980339]
   [ 0.12370675  1.7254846  -0.18347277]
   [-0.60229737 -1.645244   -1.6678892 ]
   [ 1.4236411  -0

In [59]:

import tensorflow as tf
# isort: off
from tensorflow.python.util.tf_export import keras_export

# The inputs are 28x28 RGB images with `channels_last` and the batch
# size is 4.
input_shape = (1,2, 5, 5, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(2, 3, activation='relu', input_shape=input_shape[1:])(x)
print(y.shape)
print("input=",x)
print("---------------------------------------")
print("output=",y)

(1, 2, 3, 3, 2)
input= tf.Tensor(
[[[[[ 1.765765    0.3349284  -0.27724525]
    [ 0.0621691  -0.31026882  0.12915438]
    [ 0.62063575 -0.9129284  -1.0120124 ]
    [ 0.82627636  1.0251595   0.7616905 ]
    [-0.7849966   1.1934785  -0.84708524]]

   [[ 0.93705773  0.03547988  1.4106635 ]
    [ 0.42138243  0.9291529   0.25300732]
    [ 0.52711457  2.412981   -0.04238333]
    [-1.5885361  -0.34140858  0.57470137]
    [-0.37063956 -0.4676329  -0.36877227]]

   [[-0.72427255 -1.3275187  -1.3595393 ]
    [ 0.4715843  -1.0462447  -0.66239315]
    [ 1.5193518   1.2577916   1.2300574 ]
    [-0.33677217 -0.4879411  -0.01964269]
    [ 1.0905669   0.6059493   0.48190725]]

   [[ 0.01560665 -0.38264486  0.39769372]
    [ 0.81166905 -1.1167473   0.30665568]
    [-0.66904545 -0.84275967 -0.798062  ]
    [-0.31081694 -0.13733603  1.8605074 ]
    [-1.177226   -0.590587   -1.431748  ]]

   [[-0.70953155  0.17298013  1.0683159 ]
    [ 1.4857328  -0.69317675  1.198135  ]
    [ 0.10401926  0.73356616  0.61